// Default medication overrides that are deployed with the application
// These values persist across deployments and don't require localStorage

import type { MedicationOverride } from "./adminOverrides"
// Default medication overrides
export const DEFAULT_OVERRIDES: MedicationOverride[] = [
  {
    "medication": "Zithromax",
    "doseFormula": "12 * weightKg",
    "frequency": "Once Daily",
    "reference": "Up to 12 mg/kg/day",
    "comment": "May be used as 30 mg/kg as a single dose in case of acute otitis media",
    "ageLabel": "",
    "doseMl": "Dose Formula * Concentration (mL) / Concentration (mg) / 1",
    "concentrationMg": 300,
    "concentrationMl": 7.5,
    "referenceUrl": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=071e71b8-bb53-4075-9bda-2ec48affa018",
    "maxDose": 500
  },
  {
    "medication": "Klacid 250",
    "doseFormula": "15 * weightKg",
    "frequency": "Every 12 hours",
    "reference": "15 mg/kg/day",
    "referenceUrl": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=another-id",
    "maxDose": 1000,
    "comment": "",
    "ageLabel": "",
    "doseMl": "",
    "concentrationMg": 250,
    "concentrationMl": 5
  },
  {
    "medication": "Klacid 125",
    "doseFormula": "15 * weightKg",
    "frequency": "Every 12 hours",
    "reference": "15 mg/kg/day",
    "referenceUrl": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=another-id",
    "maxDose": 1000,
    "comment": "",
    "ageLabel": "",
    "doseMl": "",
    "concentrationMg": 125,
    "concentrationMl": 5
  },
  {
    "medication": "Suprax 100",
    "doseFormula": "8 * weightKg",
    "frequency": "Once daily",
    "reference": "8 mg/kg/day",
    "referenceUrl": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=another-id",
    "maxDose": 400,
    "comment": "",
    "ageLabel": "",
    "doseMl": "",
    "concentrationMg": 100,
    "concentrationMl": 5
  },
  {
    "medication": "Amoxicillin 250",
    "doseFormula": "45 * weightKg",
    "frequency": "Every 12 hours",
    "reference": "45 mg/kg/day",
    "referenceUrl": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=another-id",
    "maxDose": 4000,
    "comment": "",
    "ageLabel": "",
    "doseMl": "",
    "concentrationMg": 250,
    "concentrationMl": 5
  },
  {
    "medication": "Augmentin 457",
    "doseFormula": "90 * weightKg",
    "frequency": "Every 12 hours",
    "reference": "90 mg/kg/day (3mo-12y)",
    "referenceUrl": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b897c800-24a2-4e76-8668-498c5515c3d0",
    "maxDose": 3600,
    "comment": "",
    "minAgeMonths": 3,
    "maxAgeMonths": 144,
    "ageLabel": "3 months - 12 years",
    "doseMl": "",
    "concentrationMg": 400,
    "concentrationMl": 5,
    "maxWeightKg": 40,
    "medication2": "Clavulanic Acid",
    "concentrationMg2": 57,
    "concentrationMl2": 5,
    "maxDose2": "10 * weightKg"
  },
  {
    "medication": "Augmentin 457",
    "doseFormula": "30 * weightKg",
    "frequency": "Every 12 hours",
    "reference": "30 mg/kg/day (3mo-12y)",
    "referenceUrl": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b897c800-24a2-4e76-8668-498c5515c3d0",
    "comment": "",
    "minAgeMonths": 0,
    "maxAgeMonths": 3,
    "ageLabel": "Under 3 months",
    "doseMl": "",
    "concentrationMg": 400,
    "concentrationMl": 5,
    "medication2": "Clavulanic Acid",
    "concentrationMg2": 57,
    "concentrationMl2": 5,
    "doseMl2": "",
    "maxDose2": "10 * weightKg"
  },
  {
    "medication": "Augmentin ES 600",
    "doseFormula": "90 * weightKg",
    "frequency": "Every 12 hours",
    "reference": "90 mg/kg/day (3mo-12y)",
    "referenceUrl": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b897c800-24a2-4e76-8668-498c5515c3d0",
    "maxDose": 3600,
    "comment": "",
    "minAgeMonths": 3,
    "maxAgeMonths": 144,
    "ageLabel": "3 months - 12 years",
    "doseMl": "",
    "concentrationMg": 600,
    "concentrationMl": 5,
    "medication2": "Clavulanic Acid",
    "concentrationMg2": 42.9,
    "concentrationMl2": 5,
    "doseMl2": "",
    "maxDose2": "10 * weightKg",
    "maxWeightKg": 40
  },
  {
    "medication": "Augmentin ES 600",
    "doseFormula": "30 * weightKg",
    "frequency": "Every 12 hours",
    "reference": "30 mg/kg/day (3mo-12y)",
    "referenceUrl": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b897c800-24a2-4e76-8668-498c5515c3d0",
    "comment": "",
    "minAgeMonths": 0,
    "maxAgeMonths": 3,
    "ageLabel": "Under 3 months",
    "doseMl": "",
    "concentrationMg": 600,
    "concentrationMl": 5,
    "medication2": "Clavulanic Acid",
    "concentrationMg2": 42.9,
    "concentrationMl2": 5,
    "doseMl2": "",
    "maxDose2": "10 * weightKg"
  },
  {
    "medication": "Metronidazole 250",
    "doseFormula": "50 * weightKg",
    "frequency": "Every 8 hours",
    "reference": "50 mg/kg/day",
    "referenceUrl": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=another-id",
    "maxDose": 2250,
    "comment": "maximum 750 mg/dose",
    "minAgeMonths": 3,
    "maxAgeMonths": 144,
    "ageLabel": "",
    "doseMl": "",
    "concentrationMg": 250,
    "concentrationMl": 5,
    "medication2": "",
    "doseMl2": "",
    "maxWeightKg": 40
  },
  {
    "medication": "Metronidazole 125",
    "doseFormula": "50 * weightKg",
    "frequency": "Every 8 hours",
    "reference": "50 mg/kg/day",
    "referenceUrl": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=another-id",
    "maxDose": 2250,
    "comment": "maximum 750 mg/dose",
    "minAgeMonths": 3,
    "maxAgeMonths": 144,
    "ageLabel": "",
    "doseMl": "",
    "concentrationMg": 125,
    "concentrationMl": 5,
    "medication2": "",
    "doseMl2": "",
    "maxWeightKg": 40
  },
  {
    "medication": "Nitrofurantoin",
    "doseFormula": "7 * weightKg",
    "frequency": "Divided into 4 doses",
    "reference": "7 mg/kg/day (3mo-12y)",
    "referenceUrl": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=dd99ba40-edff-47c3-9ee4-7e5b7774e5b5",
    "comment": "For UTI prophylaxis - take with food",
    "minAgeMonths": 3,
    "maxAgeMonths": 144,
    "ageLabel": "",
    "doseMl": "((dose*5)/25)/4",
    "concentrationMg": 25,
    "concentrationMl": 5,
    "medication2": "",
    "doseMl2": "",
    "maxWeightKg": 40
  },
  {
    "medication": "Nystatin",
    "doseFormula": "800000",
    "frequency": "4 times daily",
    "reference": "800,000 units/day (<3mo) or 2,400,000 units/day (3mo-12y)",
    "referenceUrl": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=90a52c3f-3ef7-4f3b-9fe5-40af408e9f2a",
    "comment": "",
    "minAgeMonths": 0,
    "maxAgeMonths": 12,
    "ageLabel": "Under 3 months",
    "doseMl": "(dose/100000)/4",
    "concentrationMg": 100000,
    "concentrationMl": 1,
    "medication2": "",
    "doseMl2": ""
  },
  {
    "medication": "Nystatin",
    "doseFormula": "2400000",
    "frequency": "4 times daily",
    "reference": "800,000 units/day (<3mo) or 2,400,000 units/day (3mo-12y)",
    "referenceUrl": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=90a52c3f-3ef7-4f3b-9fe5-40af408e9f2a",
    "comment": "",
    "minAgeMonths": 12,
    "maxAgeMonths": 144,
    "ageLabel": "3 months - 12 years",
    "doseMl": "(dose/100000)/4",
    "concentrationMg": 100000,
    "concentrationMl": 1,
    "medication2": "",
    "doseMl2": ""
  },
  {
    "medication": "Zovirax",
    "doseFormula": "80 * weightKg",
    "frequency": "5 times daily",
    "reference": "80 mg/kg/day (2y-12y)",
    "referenceUrl": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2ca1395f-96b4-4543-8eed-bd07c62bbc7c",
    "comment": "",
    "minAgeMonths": 24,
    "maxAgeMonths": 144,
    "ageLabel": "2-12 years",
    "doseMl": "",
    "concentrationMg": 400,
    "concentrationMl": 5,
    "medication2": "",
    "doseMl2": "",
    "maxWeightKg": 40
  },
  {
    "medication": "Zovirax",
    "doseFormula": "0",
    "frequency": "5 times daily",
    "reference": "80 mg/kg/day (2y-12y)",
    "referenceUrl": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2ca1395f-96b4-4543-8eed-bd07c62bbc7c",
    "comment": "",
    "minAgeMonths": 0,
    "maxAgeMonths": 24,
    "ageLabel": "Under 2 years (not recommended)",
    "doseMl": "",
    "concentrationMg": 400,
    "concentrationMl": 5,
    "medication2": "",
    "doseMl2": ""
  },
  {
    "medication": "Septrin (SULFAMETHOXAZOLE)",
    "doseFormula": "100 * weightKg",
    "frequency": "Every 12 hours",
    "reference": "100 mg/kg/day",
    "referenceUrl": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06e3d76b-8f16-4d53-bb9f-201cb6a72fb8",
    "maxDose": 1600,
    "comment": "",
    "minAgeMonths": 3,
    "maxAgeMonths": 144,
    "ageLabel": "",
    "doseMl": "",
    "concentrationMg": 200,
    "concentrationMl": 5,
    "medication2": "Trimethoprim",
    "concentrationMg2": 40,
    "concentrationMl2": 5,
    "doseMl2": "",
    "maxDose2": "320",
    "maxWeightKg": 40
  },
  {
    "medication": "Septrin (TRIMETHOPRIM)",
    "doseFormula": "20 * weightKg",
    "frequency": "Every 12 hours",
    "reference": "20 mg/kg/day",
    "referenceUrl": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06e3d76b-8f16-4d53-bb9f-201cb6a72fb8",
    "maxDose": 320,
    "comment": "",
    "minAgeMonths": 3,
    "maxAgeMonths": 144,
    "ageLabel": "",
    "doseMl": "",
    "concentrationMg": 40,
    "concentrationMl": 5,
    "medication2": "SULFAMETHOXAZOLE",
    "concentrationMg2": 200,
    "concentrationMl2": 5,
    "doseMl2": "",
    "maxDose2": "1600",
    "maxWeightKg": 40
  }
]
